name: Compile ESPHome
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: esphome/build-action@v2.2.0
        with:
          yaml_file: victron100.yaml
          version: latest
      - uses: actions/upload-artifact@v4
        with:
          name: victron-bin
          path: .esphome/build/victron100/.pioenvs/victron100/firmware.bin
